---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/ossdemo 
    tag: latest

params:
  ATLAS_ORG_ID:
  ATLAS_USERNAME:
  ATLAS_API_KEY:
  ATLAS_PROJECT_NAME:
  
inputs:
    - name: source-code

run:
    path: source-code/ci/tasks/atlas/create-atlas-cluster.sh
